import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/theme";
import Layout from "./components/Layout";
import react from 'react'
import Navigation from "./components/Navigation";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ThemeProvider>
        <body>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}


